image: docker:latest

services:
  - docker:dind

stages:
  - build
  - push

before_script:
  - docker info

build-docker-image:
  stage: build
  script:
    - docker build -t rag-image-search:latest

#docker-Push
 #stage:push
 #script:
  #- code to push the docker image
